# Generated by Django 4.2.8 on 2023-12-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DISPOSITIVOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AIRE_ACONDICIONADO', models.BooleanField()),
                ('ASPIRADORA', models.BooleanField()),
                ('REFRIGERADORA', models.BooleanField()),
                ('TELEVISOR', models.BooleanField()),
                ('DUCHA_ELECTRICA', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MedidorDeConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='registroDispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoKwh', models.FloatField()),
                ('tiempoDeUso', models.DateField()),
                ('cantidadDispositivos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=90)),
                ('cedula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAnalisis', models.DateField()),
                ('infoUsuario', models.CharField(max_length=80)),
                ('resultadosAlmacenados', models.CharField(max_length=80)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamoList', to='aplicacion.usuario')),
            ],
        ),
    ]
